language: python
python:
  - "2.7"
  - "3.3"
  - "pypy"
install:
  - pip install nose coverage
  - python setup.py develop
script: 
  - nosetests --with-coverage --cover-package=mtj.jibber --with-doctest --doctest-options=+ELLIPSIS
after_success:
  - pip install coveralls
  - coveralls

branches:
  only:
    -master
