language: python
python:
  - "2.7"
  - "3.3"
  - "3.4"
  - "pypy"
install:
  - pip install nose coverage
  - python setup.py develop
script: 
  - nosetests --with-coverage --cover-package=mtj.jibber --with-doctest --doctest-options=+ELLIPSIS
sudo: false
after_success:
  - pip install coveralls
  - coveralls
branches:
  only:
    - master
    - 0.3.x
    - 0.4.x
